version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/apache-tomcat-8.5.38/webapps/spring4basic
hooks:

  BeforeInstall:
    - location: script/executedeploy.sh

  AfterInstall:
    - location: script/code.sh
    - location: script/start.sh

