version: 0.0


phases:
  install:
    # Ubuntu 표준 이미지 2.0 이상을 사용하는 경우 런타임 버전을 지정해야 합니다.
    # 런타임 버전을 지정하는 경우 Ubuntu 표준 이미지 2.0 이외의 이미지를 사용하면 빌드에 실패합니다.
    runtime-versions:
      java: corretto8

  build:
    commands:
      - mvn install
  post_build:
    commands:
      - echo $(basename /home/ec2-user/apache-tomcat-8.5.38/webapps/spring4basic/*)
      - mvn clean package


artifacts:
  files:
    - target/*
    - appspec.yml
    - scripts/*
    discard-paths:yes








